### ISSUE TITLE
Update Tech Stack "Netlify", "Pingdom" and Engineering "Hosting" sections

### ISSUE THREAD

**Issue by DouweM** [meltano/handbook#323]
https://handbook.meltano.com/company/tech-stack/#netlify, https://handbook.meltano.com/company/tech-stack/#pingdom, and https://handbook.meltano.com/engineering/#domain-names-dns-and-hosting are out dated as docs.meltano.com and handbook.meltano.com are now hosted on Netlify and monitored using Pingdom. 

@aaronsteers Can someone on your team please update this since these are owned by Eng?

**Comment by aaronsteers** [comment]
@DouweM - Thanks for raising. 

@pandemicsyn - assigning to you, as I think you probably have the best view on how all are setup and managed as of now. Lmk if I can help at all.

**Comment by pandemicsyn** [comment]
> @pandemicsyn - assigning to you, as I think you probably have the best view on how all are setup and managed as of now. Lmk if I can help at all.

I can take a look at what the current Netlify configs are and update accordingly. I'm actually not positive how everything is setup (pingdom, dns, etc). But I can poke around and farm out questions as needed (i.e. do we even still use site-ground for anything since we switched to wp-engine?)

**Comment by aaronsteers** [comment]
Thanks, @pandemicsyn. Appreciate you diving in here to research + update these.
