### ISSUE TITLE
Create official policy around who should be a Slack Workspace admin

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/handbook#372]
Unofficially we were making most (all?) Meltano employees workspace admins. Obviously we don't want to continue making all employees workspace admins, and that confers a huge amount of power that few truly need.

**Comment by afolson** [comment]
Related: https://github.com/meltano/internal-general/issues/399

**Comment by WillDaSilva** [comment]
I'm closing this issue as a duplicate. Thanks @afolson
