### ISSUE TITLE
Add domain purchase policy to handbook

### ISSUE THREAD

**Issue by therebbie** [meltano/handbook#398]
- Info on vendor(s) -- Default to AWS / Namecheap wherever possible. We really want as few registrar accounts as possible
- Use hello@meltano.com for notifications and ap@meltano.com for billing.  
- DNS should be handled via Route 53 (AWS) or Cloudflare -- nowhere else
- Make sure to update the spreadsheet that tracks what we've got.

**Comment by DouweM** [comment]
@therebbie Sounds good to me.

@aaronsteers Any concerns? This came up because we'd registered meltano.cloud but it wasn't tracked in our domains sheet.

**Comment by therebbie** [comment]
@WillDaSilva the [spreadsheet is here.](https://docs.google.com/spreadsheets/d/15f_p0jU1ZaIMPE8_3OTBjM5Uf5_RjtG8EIRUygFVBTM/edit?usp=sharing)

**Comment by aaronsteers** [comment]
> @therebbie Sounds good to me.
> 
> @aaronsteers Any concerns? This came up because we'd registered meltano.cloud but it wasn't tracked in our domains sheet.

No concern from my side. Once we have a PR, we can do a quick PSA in `#internal-engineering` with a link to the handbook page. 

Search is broken (at least for me) in the handbook, but a search for "domains" leads to Marketing Ops, which I can navigate to manually here: 

- https://handbook.meltano.com/marketing/marketing-ops/#domains

> ![image](https://user-images.githubusercontent.com/18150651/224144003-58e52674-ff82-4926-8604-881e021d98fc.png)

Also probably worth noting or cross-referencing to relevant items here:

- https://handbook.meltano.com/company/tech-stack/

**Comment by therebbie** [comment]
@aaronsteers the PR I came up with is here: https://github.com/meltano/handbook/pull/399 I didn't want address/email info on our site.

**Comment by therebbie** [comment]
I pushed & merged. This is done now.
